Repository explore-siargao/es-main, pull requests merged in 2024-05, with the labels that each got.

#16 [Story-Feature] Created documentation for creating task and branch option 1
  docs/task-creation/images/step1.0.png
  docs/task-creation/images/step10.0.png
  docs/task-creation/images/step10.1.png
  docs/task-creation/images/step11.0.png
  docs/task-creation/images/step12.0.png
  docs/task-creation/images/step13.0.png
  docs/task-creation/images/step13.1.png
  docs/task-creation/images/step13.2.png
  docs/task-creation/images/step14.0.png
  docs/task-creation/images/step16.0.png
  docs/task-creation/images/step17.0.png
  docs/task-creation/images/step17.1.png
  docs/task-creation/images/step19.0.png
  docs/task-creation/images/step19.1.png
  docs/task-creation/images/step2.0.png
  docs/task-creation/images/step20.0.png
  docs/task-creation/images/step20.1.png
  docs/task-creation/images/step20.2.png
  docs/task-creation/images/step3.0.png
  docs/task-creation/images/step5.0.png
  docs/task-creation/images/step6.0.png
  docs/task-creation/images/step8.0.png
  docs/task-creation/images/step9.0.png
  docs/task-creation/task_creation_option_1.md
  pnpm-lock.yaml
Labels: documentation, task

#14 [Story-Feature] Added get rental rates endpoints
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/rates.ts
  pnpm-lock.yaml
Labels: backend, task, host account

#15 [Story-Feature] Created update rental rates endpoint
  apps/api/src/common/helpers/prismaClient.ts
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/api/src/routes/api/rentals-v2/services/rates.ts
  packages/database/mongo/models/dbRentalRates.ts
Labels: backend, task, host account

#28 [Task-Story] Story rental photos endpoint
  apps/api/package.json
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/api/src/routes/api/rentals-v2/services/photos.ts
  packages/database/mongo/models/dbRentals.ts
  pnpm-lock.yaml
Labels: backend, task, host account

#30 [Task-Story] update rental photos endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/photos.ts
Labels: database, backend, task

#31 [Docs - Feature] Created Task creation option 2 documentation
  docs/task_creation/images/2step1.0.png
  docs/task_creation/images/2step10.0.png
  docs/task_creation/images/2step10.1.png
  docs/task_creation/images/2step11.0.png
  docs/task_creation/images/2step11.1.png
  docs/task_creation/images/2step11.2.png
  docs/task_creation/images/2step11.3.png
  docs/task_creation/images/2step12.0.png
  docs/task_creation/images/2step12.1.png
  docs/task_creation/images/2step12.2.png
  docs/task_creation/images/2step12.3.png
  docs/task_creation/images/2step13.0.png
  docs/task_creation/images/2step14.0.png
  docs/task_creation/images/2step14.1.png
  docs/task_creation/images/2step14.2.png
  docs/task_creation/images/2step14.3.png
  docs/task_creation/images/2step15.0.png
  docs/task_creation/images/2step15.1.png
  docs/task_creation/images/2step15.2.png
  docs/task_creation/images/2step2.0.png
  docs/task_creation/images/2step3.0.png
  docs/task_creation/images/2step5.0.png
  docs/task_creation/images/2step6.0.png
  docs/task_creation/images/2step8.0.png
  docs/task_creation/images/2step9.0.png
  docs/task_creation/task_creation_option_2.md
Labels: documentation, host account

#32 [Task-Story] Story edit photo info endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/photos.ts
Labels: backend, task, host account

#33 [Feature - Epic ] Docs general documentation
  docs/task-creation/images/step1.0.png
  docs/task-creation/images/step10.0.png
  docs/task-creation/images/step10.1.png
  docs/task-creation/images/step11.0.png
  docs/task-creation/images/step12.0.png
  docs/task-creation/images/step13.0.png
  docs/task-creation/images/step13.1.png
  docs/task-creation/images/step13.2.png
  docs/task-creation/images/step14.0.png
  docs/task-creation/images/step16.0.png
  docs/task-creation/images/step17.0.png
  docs/task-creation/images/step17.1.png
  docs/task-creation/images/step19.0.png
  docs/task-creation/images/step19.1.png
  docs/task-creation/images/step2.0.png
  docs/task-creation/images/step20.0.png
  docs/task-creation/images/step20.1.png
  docs/task-creation/images/step20.2.png
  docs/task-creation/images/step3.0.png
  docs/task-creation/images/step5.0.png
  docs/task-creation/images/step6.0.png
  docs/task-creation/images/step8.0.png
  docs/task-creation/images/step9.0.png
  docs/task-creation/task_creation_option_1.md
  docs/task_creation/images/2step1.0.png
  docs/task_creation/images/2step10.0.png
  docs/task_creation/images/2step10.1.png
  docs/task_creation/images/2step11.0.png
  docs/task_creation/images/2step11.1.png
  docs/task_creation/images/2step11.2.png
  docs/task_creation/images/2step11.3.png
  docs/task_creation/images/2step12.0.png
  docs/task_creation/images/2step12.1.png
  docs/task_creation/images/2step12.2.png
  docs/task_creation/images/2step12.3.png
  docs/task_creation/images/2step13.0.png
  docs/task_creation/images/2step14.0.png
  docs/task_creation/images/2step14.1.png
  docs/task_creation/images/2step14.2.png
  docs/task_creation/images/2step14.3.png
  docs/task_creation/images/2step15.0.png
  docs/task_creation/images/2step15.1.png
  docs/task_creation/images/2step15.2.png
  docs/task_creation/images/2step2.0.png
  docs/task_creation/images/2step3.0.png
  docs/task_creation/images/2step5.0.png
  docs/task_creation/images/2step6.0.png
  docs/task_creation/images/2step8.0.png
  docs/task_creation/images/2step9.0.png
  docs/task_creation/task_creation_option_2.md
  pnpm-lock.yaml
Labels: documentation, story, host account

#34 [Hotfix] Make prettier format workflow apply to all branch
  .github/workflows/prettier-format.yml
  CHANGELOG.md
  docs/github_project/task_creation_option_1.md
  docs/github_project/task_creation_option_2.md
  docs/task-creation/images/step1.0.png
  docs/task-creation/images/step10.0.png
  docs/task-creation/images/step10.1.png
  docs/task-creation/images/step11.0.png
  docs/task-creation/images/step12.0.png
  docs/task-creation/images/step13.0.png
  docs/task-creation/images/step13.1.png
  docs/task-creation/images/step13.2.png
  docs/task-creation/images/step14.0.png
  docs/task-creation/images/step16.0.png
  docs/task-creation/images/step17.0.png
  docs/task-creation/images/step17.1.png
  docs/task-creation/images/step19.0.png
  docs/task-creation/images/step19.1.png
  docs/task-creation/images/step2.0.png
  docs/task-creation/images/step20.0.png
  docs/task-creation/images/step20.1.png
  docs/task-creation/images/step20.2.png
  docs/task-creation/images/step3.0.png
  docs/task-creation/images/step5.0.png
  docs/task-creation/images/step6.0.png
  docs/task-creation/images/step8.0.png
  docs/task-creation/images/step9.0.png
  docs/task_creation/images/2step1.0.png
  docs/task_creation/images/2step10.0.png
  docs/task_creation/images/2step10.1.png
  docs/task_creation/images/2step11.0.png
  docs/task_creation/images/2step11.1.png
  docs/task_creation/images/2step11.2.png
  docs/task_creation/images/2step11.3.png
  docs/task_creation/images/2step12.0.png
  docs/task_creation/images/2step12.1.png
  docs/task_creation/images/2step12.2.png
  docs/task_creation/images/2step12.3.png
  docs/task_creation/images/2step13.0.png
  docs/task_creation/images/2step14.0.png
  docs/task_creation/images/2step14.1.png
  docs/task_creation/images/2step14.2.png
  docs/task_creation/images/2step14.3.png
  docs/task_creation/images/2step15.0.png
  docs/task_creation/images/2step15.1.png
  docs/task_creation/images/2step15.2.png
  docs/task_creation/images/2step2.0.png
  docs/task_creation/images/2step3.0.png
  docs/task_creation/images/2step5.0.png
  docs/task_creation/images/2step6.0.png
  docs/task_creation/images/2step8.0.png
  docs/task_creation/images/2step9.0.png
Labels: documentation, enhancement

#36 [Story-Feature] Added delete rental photo endpoint
  apps/api/src/common/helpers/prismaClient.ts
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/api/src/routes/api/rentals-v2/services/photos.ts
  apps/api/src/routes/api/rentals-v2/services/rates.ts
  packages/database/mongo/models/dbRentals.ts
Labels: backend, task, host account

#37 [Story-Feature] Added get rental location v2 endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/locations.ts
Labels: backend, task, host account

#38 [Story-Feature] Added api v2 get finished section endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/details.ts
  apps/api/src/routes/api/rentals-v2/services/finishedSections.ts
  apps/api/src/routes/api/rentals-v2/services/photos.ts
  apps/api/src/routes/api/rentals-v2/services/rates.ts
  packages/database/mongo/models/dbRentals.ts
Labels: backend, task, host account

#39 [Story-Feature] Added update Rental Location endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/locations.ts
  packages/contract/src/Rental/type.ts
  packages/contract/src/Rental/zod.ts
Labels: backend, task, host account

#40 [Story-Feature] Added update rental status endpoint in api v2
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/locations.ts
  apps/api/src/routes/api/rentals-v2/services/status.ts
  packages/contract/src/Rental/type.ts
Labels: backend, task, host account

#41 [Story-Feature] Added get addons endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/addOns.ts
  packages/contract/src/Rental/zod.ts
Labels: backend, task, host account

#43 [Story-Feature] Added update finished sections endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/finishedSections.ts
  apps/api/src/routes/api/rentals-v2/services/locations.ts
Labels: backend, task, host account

#65 [Story-Feature] Created isHostRentalOwner2 middleware and apply it to index.ts
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/mock/rentals/middleware/isHostRentalOwner2.ts
Labels: backend, task, host account

#66 [Story-Feature] Added update addons endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/addOns.ts
Labels: backend, task, host account
