Repository explore-siargao/es-main, pull requests merged in 2024-08, with the labels that each got.

#661 [Story-Feature] Add qty to rentals motorcycle and bikes UI and backend
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
  packages/contract/src/Rental/zod.ts
Labels: backend, frontend, task, host account

#662 [Story-Feature] Rental Search pick up and drop date
  apps/web/common/components/Footer/index.tsx
  apps/web/common/components/Header.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/module/LandingPage/components/ImageTextCard.tsx
  apps/web/module/LandingPage/index.tsx
Labels: frontend, task, host account

#664 [Task-Story] Complete home page UI
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/SliderItem.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
Labels: frontend, task, host account

#665 [Story-Feature] Created reusable adjustablefilter component
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/common/assets/bargraph.png
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Photos.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useBedroomStore.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/constants/index.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/types/index.ts
  apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceBasicInfo.ts
  apps/web/module/LandingPage/index.tsx
  apps/web/package.json
  packages/database/mongo/models/dbBookableUnitTypes.ts
  pnpm-lock.yaml
Labels: frontend, task, host account

#663 [ Story - Feature ] Put image name etc when hover on pin in guide map
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/common/components/SpecificMap.tsx
  apps/web/module/Accommodation/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/Guides/Islands/index.tsx
  apps/web/module/Guides/Restaurant/index.tsx
  apps/web/module/Guides/Surfing/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
  apps/web/module/Guides/data.json
Labels: frontend, task, host account

#666 [Story-Feature] Updates 579 from 635
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/common/components/SpecificMap.tsx
  apps/web/module/Accommodation/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/Guides/Islands/index.tsx
  apps/web/module/Guides/Restaurant/index.tsx
  apps/web/module/Guides/Surfing/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
  apps/web/module/Guides/data.json
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
  packages/contract/src/BookableUnitType/zod.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: story, backend, frontend, host account

#675 [Task-Story] Remove items on inspirational
  apps/web/app/(properties)/properties/[category]/layout.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/module/TravelStyle/components/TravelStyleContainer.tsx
  apps/web/module/TravelStyle/components/TravelStyleItem.tsx
  apps/web/module/TravelStyle/index.tsx
Labels: frontend, task, host account

#676 [Story - Feature] Update sprint 4 priorities branch for all updates from Improved home page
  apps/web/app/(properties)/properties/[category]/layout.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/module/TravelStyle/components/TravelStyleContainer.tsx
  apps/web/module/TravelStyle/components/TravelStyleItem.tsx
  apps/web/module/TravelStyle/index.tsx
Labels: story, backend, frontend, host account

#682 [Story-Feature] Create side filter reusable component
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/common/components/Filters/Minimap.tsx
  apps/web/common/components/Filters/NumericFilter/index.tsx
  apps/web/common/components/Filters/SideFilter.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
Labels: frontend, task, host account

#683 [Story-Feature] Updates from improve home page to sprint 4
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/common/components/Filters/Minimap.tsx
  apps/web/common/components/Filters/NumericFilter/index.tsx
  apps/web/common/components/Filters/SideFilter.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
Labels: story, frontend

#685 [Feature - Story] Sync story branch for updated code from feature branch
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/common/components/SpecificMap.tsx
  apps/web/module/Accommodation/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/Guides/Islands/index.tsx
  apps/web/module/Guides/Restaurant/index.tsx
  apps/web/module/Guides/Surfing/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
  apps/web/module/Guides/data.json
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/Bed.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/components/UnitsTable.tsx
  packages/contract/src/BookableUnitType/zod.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: enhancement, feature, frontend

#686 [Task-Story] Added level and cuisine to popup on guide map
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/module/Guides/Restaurant/index.tsx
  apps/web/module/Guides/Surfing/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
Labels: frontend, task, host account

#687 [Task-Story] Changed link and url behaviour of SliderItem
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/SliderItem.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, frontend, task

#688 [Task-feature] Modified slider to accept how many items will display
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, frontend, task

#690 [Story - Feature] Updates from 7-30-2024 comments to sprint 4 priorities
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
  packages/contract/src/Rental/zod.ts
Labels: enhancement, story, backend, frontend

#692 [Task-Story] Create reusable component for the filter result
  apps/web/module/LandingPage/components/CardList.tsx
  apps/web/module/LandingPage/index.tsx
Labels: frontend, task

#693 [Task-Story] Added api endpoint for getting rental bike calendar view
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  packages/database/mongo/models/dbRentals.ts
Labels: backend, task, host account

#695 [Story-Feature] Payload cms for surfing
  apps/web/app/(guides)/guides/layout.tsx
  apps/web/common/constants/ev.ts
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/module/Accommodation/components/modals/ImageGalleryModal.tsx
  apps/web/module/Accommodation/types/SectionInfo.d.ts
  apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/SurfGuide.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/next.config.js
Labels: story, frontend, host account

#696 [Task-Story] Added endpoint for calendar rental motorcycle
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
Labels: enhancement, backend, task

#701 [Task - Story] Implemented calendar reservation for motorcycle in frontend
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/ReservationCalendarModal.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: backend, frontend, task

#702 [Story - Feature] Added backend for bike and motor calendar reservation and implement motor calendar to frontend
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/ReservationCalendarModal.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  packages/database/mongo/models/dbRentals.ts
Labels: story, backend, frontend

#704 [Feature - Develop] Updates from 470 reservation calendar view
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/common/components/Filters/Minimap.tsx
  apps/web/common/components/Filters/NumericFilter/index.tsx
  apps/web/common/components/Filters/SideFilter.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/ReservationCalendarModal.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  apps/web/module/LandingPage/components/TravelSlider.tsx
  packages/contract/src/Rental/zod.ts
  packages/database/mongo/models/dbRentals.ts
Labels: feature, backend, frontend

#703 [ Story - Feature ] On studio type unit you cant add room more than one
  apps/web/common/components/ui/Select.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
Labels: frontend, task, host account

#705 [Story - Feature] Edited Units Whole place and rental motorcycle and bicycles
  apps/web/common/components/ui/Select.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
Labels: enhancement, story, frontend

#707 [Story - Feature] Updates added cuisines and levels in popop in guide map and modiied slider
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/module/Guides/Restaurant/index.tsx
  apps/web/module/Guides/Surfing/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/SliderItem.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, story, frontend

#709 [Feature - Develop] Updates from PayloadCMS frontend
  apps/web/app/(guides)/guides/layout.tsx
  apps/web/common/constants/ev.ts
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/module/Accommodation/components/modals/ImageGalleryModal.tsx
  apps/web/module/Accommodation/types/SectionInfo.d.ts
  apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/SurfGuide.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/next.config.js
Labels: enhancement, feature, frontend

#710 [ Story - Feature ] On studio type unit you cant add room more than one
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useBedroomStore.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/constants/index.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/types/index.ts
  apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceBasicInfo.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: story, frontend, host account

#711 [Story-Feature] Updates from 07-30-comments
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useBedroomStore.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/constants/index.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/types/index.ts
  apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceBasicInfo.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: story, backend, frontend, host account

#712 [Feature - Develop] Updates from sprint 4 priorities
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/AddBedroomModal.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/components/Bedroom.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/store/useBedroomStore.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/constants/index.ts
  apps/web/module/Hosting/Listings/Properties/Property/Units/types/index.ts
  apps/web/module/Hosting/Listings/Properties/hooks/useUpdateWholePlaceBasicInfo.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: feature, backend, frontend, host account

#720 [Story-Feature] Connect main landing page to second page
  apps/web/app/(locations)/ClientHeroSection.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/module/Listings/index.tsx
  apps/web/module/TravelStyle/components/TravelStyleContainer.tsx
  apps/web/module/TravelStyle/components/TravelStyleItem.tsx
  apps/web/module/TravelStyle/index.tsx
Labels: frontend, task

#721 [Story-Feature] Update from second level page
  apps/web/app/(locations)/ClientHeroSection.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/module/Listings/index.tsx
  apps/web/module/TravelStyle/components/TravelStyleContainer.tsx
  apps/web/module/TravelStyle/components/TravelStyleItem.tsx
  apps/web/module/TravelStyle/index.tsx
Labels: story, frontend, host account

#722 [Feature- Develop] Update from sprint 4
  apps/web/app/(locations)/ClientHeroSection.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/module/Listings/index.tsx
  apps/web/module/TravelStyle/components/TravelStyleContainer.tsx
  apps/web/module/TravelStyle/components/TravelStyleItem.tsx
  apps/web/module/TravelStyle/index.tsx
Labels: feature, frontend, host account

#751 [Story-Feature] Payload cms for for restaurants
  apps/web/module/Accommodation/components/TitleSection.tsx
  apps/web/module/Accommodation/components/modals/ModalAboutTitleDescription.tsx
  apps/web/module/Accommodation/types/SectionInfo.d.ts
  apps/web/module/BlogGuide/Guide/RestaurantGuide/CheckoutBox.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/AmenityList.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/Contacts.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/NearbyAccommodation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/OffersCuisine.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/OpeningHours.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/PriceLevel.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/modals/BusinessHoursModal.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/modals/EventsModal.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/modals/MenuModal.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Reviews/index.tsx
  apps/web/next.config.js
Labels: frontend, host account

#757 [Task-Story] Added custom hooks for getting bike calendar reservation
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBike.ts
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
Labels: frontend, task, host account

#759 [Story-Feature] Payload cms for location directions
  apps/web/app/(blog-guide)/layout.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/module/Accommodation/types/SectionInfo.d.ts
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/OtherContents.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TopThingsToDo.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TravelChecklist.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TravelImages.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/components/RichText/serialize.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/module/BlogGuide/Header/index.tsx
  apps/web/next.config.js
  apps/web/package.json
  pnpm-lock.yaml
Labels: story, frontend, host account

#760 [Task - Story] Implemented backend get calendar rentals bike to frontendend
  apps/web/app/(host)/hosting/reservations/calendar/rentals/bicycles/page.tsx
  apps/web/app/(host)/hosting/reservations/calendar/rentals/motorcycles/page.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: frontend, task, host account

#761 [Story - Feature] Added Rental Bike Front and backend
  apps/web/app/(host)/hosting/reservations/calendar/rentals/bicycles/page.tsx
  apps/web/app/(host)/hosting/reservations/calendar/rentals/motorcycles/page.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBike.ts
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: story, backend, frontend, host account

#762 [ Story - Feature ] Lightbox image gallery
  apps/web/common/components/SliderImages.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
Labels: enhancement, story, frontend, host account

#764 [ Story - Feature ] Landing page improvements
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, feature, frontend, host account

#765 [Task - Story] Added backend car calendar reservation endpoint
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
Labels: backend, frontend, task, host account

#766 [Task-Story] All content same margin including search bar
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/module/Listings/index.tsx
Labels: enhancement, frontend, task, host account

#767 feat(web): Added custom hook for getting cars calendar reservation
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarCar.ts
Labels: frontend, task, host account

#772 [Epic - Main] Added Lightbox gallery to guides image gallery and on single page UI
  apps/web/common/components/SliderImages.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
Labels: feature, frontend, host account

#774 [Task-Story] Edit side filter make it standout
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/common/components/Filters/Minimap/index.tsx
  apps/web/common/components/Filters/NumericFilter/index.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/module/Listings/components/SideFilter.tsx
  apps/web/module/Listings/index.tsx
Labels: enhancement, frontend, host account

#775 [Story- Fature] Added dynamic side filters and changed column number of items
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/common/components/Filters/Minimap/index.tsx
  apps/web/common/components/Filters/NumericFilter/index.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/module/Listings/components/SideFilter.tsx
  apps/web/module/Listings/index.tsx
Labels: story, frontend, host account

#776 [Epic - Main] Modified landing page and 2nd page
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/Filters/BudgetFilter/BudgetSlider.tsx
  apps/web/common/components/Filters/CheckBoxFilter/index.tsx
  apps/web/common/components/Filters/Minimap/index.tsx
  apps/web/common/components/Filters/NumericFilter/index.tsx
  apps/web/common/components/SearchBar.tsx
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/module/Listings/components/SideFilter.tsx
  apps/web/module/Listings/index.tsx
Labels: enhancement, feature, frontend, host account

#771 [Epic-Main] Applied payloadcms to frontend guide ang blog
  apps/web/app/(blog-guide)/layout.tsx
  apps/web/common/components/CustomSpecificMap.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/module/Accommodation/components/TitleSection.tsx
  apps/web/module/Accommodation/components/modals/ModalAboutTitleDescription.tsx
  apps/web/module/Accommodation/types/SectionInfo.d.ts
  apps/web/module/BlogGuide/Guide/RestaurantGuide/CheckoutBox.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/AmenityList.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/Contacts.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/NearbyAccommodation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/OffersCuisine.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/OpeningHours.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/PriceLevel.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/modals/BusinessHoursModal.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/modals/EventsModal.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/modals/MenuModal.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/Directions.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/SurfGuide.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/OtherContents.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TopThingsToDo.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TravelChecklist.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TravelImages.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/components/RichText/serialize.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/module/BlogGuide/Header/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Reviews/index.tsx
  apps/web/next.config.js
  apps/web/package.json
  pnpm-lock.yaml
Labels: feature, frontend, host account

#770 [EPIC- Main] Added calendar view on all rentals
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  apps/web/app/(host)/hosting/reservations/calendar/rentals/bicycles/page.tsx
  apps/web/app/(host)/hosting/reservations/calendar/rentals/cars/page.tsx
  apps/web/app/(host)/hosting/reservations/calendar/rentals/motorcycles/page.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/BasicInfo/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/AddReservationModal/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBike.ts
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarCar.ts
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarMotor.ts
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: feature, backend, frontend, host account

#777 [Task-Story] Edit side filter make it standout
  apps/web/common/components/SearchBar.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, frontend, host account

#778 Release 0.8.1
  .github/workflows/deploy-home-manual.yml
  .github/workflows/deploy-home.yml
  .gitignore
  apps/web/next.config.js
  docker/api/Dockerfile
  docker/api/Dockerfile.arm
  docker/api/compose-arm.yml
  docker/api/compose.yml
  docker/compose-arm-sit.yml
  docker/compose-sit.yml
  docker/web/Dockerfile
  docker/web/Dockerfile.arm
  docker/web/compose-arm.yml
  docker/web/compose-build-arm.yml
  docker/web/compose-build.yml
  docker/web/compose.yml
  package.json
  packages/database/mongo/index.ts
Labels: release, patch

#781 [Story - Feature] Updates from 2nd page improvements
  apps/web/common/components/SearchBar.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, story, frontend, host account

#789 [Epic - Main ] Updates from Landing and 2nd page
  apps/web/common/components/SearchBar.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, feature, frontend, host account

#790 [Task-Story] Earnings make 3 graphs and if all selected will see full breakdown
  apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
  apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
  apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
  apps/web/module/Hosting/Earnings/components/ThisMonthChart.tsx
  apps/web/module/Hosting/Earnings/components/UpcomingChart.tsx
Labels: enhancement, frontend, task, host account

#793 [Bug - Epic] Fixed error on creating new property
  apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
  apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
  apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
  apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
  apps/web/module/LandingPage/index.tsx
Labels: bug, enhancement, frontend, host account

#794 [Epic - Main] Update from unit improvements fixed some error in creating properties
  apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
  apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
  apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
  apps/web/module/Hosting/Earnings/components/ThisMonthChart.tsx
  apps/web/module/Hosting/Earnings/components/UpcomingChart.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
  apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
  apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
  apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
  apps/web/module/LandingPage/index.tsx
Labels: bug, enhancement, feature, frontend, host account

#796 [Main to Epic] Sync Updates to Calendar Reservation from main
  CHANGELOG.md
  apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
  apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
  apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
  apps/web/module/Hosting/Earnings/components/ThisMonthChart.tsx
  apps/web/module/Hosting/Earnings/components/UpcomingChart.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
  apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
  apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
  apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
  apps/web/module/LandingPage/index.tsx
  package.json
Labels: feature, host account

#797 [Epic - Story] Sync updates from parent branch to child branch
  CHANGELOG.md
  apps/web/module/Hosting/Earnings/EarningGraphTab.tsx
  apps/web/module/Hosting/Earnings/EarningsThisMonth.tsx
  apps/web/module/Hosting/Earnings/EarningsUpcoming.tsx
  apps/web/module/Hosting/Earnings/components/ThisMonthChart.tsx
  apps/web/module/Hosting/Earnings/components/UpcomingChart.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
  apps/web/module/Hosting/Listings/hooks/useGetPropertyByHost.ts
  apps/web/module/Hosting/Listings/hooks/useGetPropertyById.ts
  apps/web/module/Hosting/Listings/hooks/useUpdatePropertyBasicInfo.ts
  apps/web/module/LandingPage/index.tsx
  package.json
Labels: enhancement, feature, host account

#798 Re-setup new empty CMS
  apps/api/package.json
  apps/cms/.gitignore
  apps/cms/README.md
  apps/cms/nodemon.json
  apps/cms/package.json
  apps/cms/src/collections/Categories/index.ts
  apps/cms/src/collections/Locations/index.ts
  apps/cms/src/collections/Media/index.ts
  apps/cms/src/collections/Restaurants/index.ts
  apps/cms/src/collections/Surfs/index.ts
  apps/cms/src/collections/Users/index.ts
  apps/cms/src/fields/locations/content.ts
  apps/cms/src/fields/locations/hero.ts
  apps/cms/src/fields/locations/sideContent.ts
  apps/cms/src/fields/restaurants/about.ts
  apps/cms/src/fields/restaurants/content.ts
  apps/cms/src/fields/restaurants/hero.ts
  apps/cms/src/fields/restaurants/location.ts
  apps/cms/src/fields/slug.ts
  apps/cms/src/fields/surfs/content.ts
  apps/cms/src/fields/surfs/hero.ts
  apps/cms/src/payload.config.ts
  apps/cms/src/server.ts
  apps/cms/src/utilities/deepMerge.ts
  apps/cms/src/utilities/formatSlug.ts
  apps/cms/tsconfig.json
  apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/next.config.js
  docker/api/Dockerfile.arm
  docker/cms/Dockerfile
  docker/cms/Dockerfile.arm
  docker/compose-arm-sit.yml
  docker/compose-sit.yml
  pnpm-lock.yaml
Labels: enhancement

#800 [Hotifx] Update secrets in deploy-home workflows
  .github/workflows/deploy-home-manual.yml
  .github/workflows/deploy-home.yml
Labels: patch

#802 [Task-Story] Landing and 2nd page UI Adjustments
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/Header.tsx
  apps/web/common/components/SearchBar/SearchBarNoHero.tsx
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
Labels: enhancement, frontend, task, host account

#801 [Story-Feature] Adjusted lightbox UI
  apps/web/common/components/SliderImages.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/next.config.js
  pnpm-lock.yaml
Labels: frontend, task, host account

#804 [Task-Story] Guide restaurants UI adjustments
  apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/next.config.js
Labels: enhancement, frontend, task, host account

#805 [Main - Epic] Sync updates from main to Units improvements
  .github/workflows/deploy-home-manual.yml
  .github/workflows/deploy-home.yml
  CHANGELOG.md
  apps/api/package.json
  apps/cms/.gitignore
  apps/cms/README.md
  apps/cms/nodemon.json
  apps/cms/package.json
  apps/cms/src/collections/Categories/index.ts
  apps/cms/src/collections/Locations/index.ts
  apps/cms/src/collections/Media/index.ts
  apps/cms/src/collections/Restaurants/index.ts
  apps/cms/src/collections/Surfs/index.ts
  apps/cms/src/collections/Users/index.ts
  apps/cms/src/fields/locations/content.ts
  apps/cms/src/fields/locations/hero.ts
  apps/cms/src/fields/locations/sideContent.ts
  apps/cms/src/fields/restaurants/about.ts
  apps/cms/src/fields/restaurants/content.ts
  apps/cms/src/fields/restaurants/hero.ts
  apps/cms/src/fields/restaurants/location.ts
  apps/cms/src/fields/slug.ts
  apps/cms/src/fields/surfs/content.ts
  apps/cms/src/fields/surfs/hero.ts
  apps/cms/src/payload.config.ts
  apps/cms/src/server.ts
  apps/cms/src/utilities/deepMerge.ts
  apps/cms/src/utilities/formatSlug.ts
  apps/cms/tsconfig.json
  apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/next.config.js
  docker/api/Dockerfile
  docker/api/Dockerfile.arm
  docker/cms/Dockerfile
  docker/cms/Dockerfile.arm
  docker/compose-arm-sit.yml
  docker/compose-sit.yml
  package.json
  pnpm-lock.yaml
  turbo.json
Labels: feature, frontend, host account

#808 [Story-Feature] Adjusted travel UI
  apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
Labels: frontend, task, host account

#809 [Task-Story] Added get room calendar reservations endpoints
  .gitignore
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/api/src/routes/api/properties-v2/services/units.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: backend, task, host account

#810 [Task-Story] Added custom hook to connect to get calendar room reservat…
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarRoom.ts
Labels: frontend, task, host account

#811 [Hotfix] PayloadCMS assets upload move to AWS
  .github/workflows/deploy-home-manual.yml
  .github/workflows/deploy-home.yml
  apps/api/src/common/service/file.ts
  apps/cms/package.json
  apps/cms/src/collections/Media/index.ts
  apps/cms/src/payload.config.ts
  docker/api/Dockerfile
  docker/api/Dockerfile.arm
  docker/cms/Dockerfile
  docker/cms/Dockerfile.arm
  docker/compose-arm-sit.yml
  docker/compose-sit.yml
  pnpm-lock.yaml
  turbo.json
Labels: enhancement, feature

#813 [Hotfix] Added release please config for custom title and section
  release-please-config.json
Labels: release, hotfix, patch

#818 [Task-Story] Added calendar reservation room view connected to backend
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/rooms/page.tsx
  apps/web/common/components/HostLayout/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Upcoming/index.tsx
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: enhancement, backend, frontend, task, host account

#819 [Story- Epic] Connected calendar reservation room frontend to backend get request
  .gitignore
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/rooms/page.tsx
  apps/web/common/components/HostLayout/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarRoom.ts
  apps/web/module/Hosting/Reservations/Upcoming/index.tsx
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: story, backend, frontend, host account

#820 [ Story - Feature ] Make the listbox square shape
  apps/web/common/components/CustomSquareSlider.tsx
  apps/web/module/Listing/components/BoxContainer.tsx
Labels: enhancement, story, frontend, host account

#822 [ Bug - Feature ] Savings of emergencycontact not working
  apps/api/src/common/middleware/auth/isUserLoggedIn3.ts
  apps/api/src/routes/api/users-v2/services/personalInfo.ts
Labels: bug, story, backend, frontend, host account

#823 [Task - Story] Added endpoint for get calendar reservations for beds
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/api/src/routes/api/properties-v2/services/units.ts
Labels: backend, task, host account

#824 [ Story - Feature ] Create endpoint for calendar unit whole place reservations
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
Labels: enhancement, backend, task, host account

#825 [Task - Story] Added custom hook for get calendar bed reservations
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBed.ts
Labels: frontend, task, host account

#826 [ Story - Feature ] Create custom hooks for get calendar unit whole place reservations
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarWholePlace.ts
Labels: frontend, task, host account

#827 [Task - Story] Connected calendar reservation beds frontend to backend
  apps/web/app/(host)/hosting/reservations/calendar/properties/beds/page.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: frontend, task, host account

#828 [Story - Epic] Added Calendar reservation beds view calendar
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/beds/page.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBed.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: story, backend, frontend, host account

#829 [Epic - Main] Update from landing page and 2nd page
  apps/web/common/components/CustomSquareSlider.tsx
  apps/web/module/Listing/components/BoxContainer.tsx
Labels: enhancement, frontend, epic, host account

#831 [Task - Story] Connected calendar unit whole place reservation backend to frontend
  apps/web/app/(host)/hosting/reservations/calendar/properties/whole-places/page.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: frontend, task, host account

#832 [Story - Epic] Added Calendar reservation whole place
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/whole-places/page.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarWholePlace.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: story, backend, frontend, host account

#833 [Task-Story] Guides surf UI adjustments
  apps/web/app/(blog-guide)/layout.tsx
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/common/components/SearchBar/SearchBar.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/next.config.js
Labels: enhancement, frontend, task, host account

#834 [Story - Epic] Improved base from comments on 08-16-2024
  apps/web/app/(blog-guide)/layout.tsx
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/Header.tsx
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/common/components/SearchBar/SearchBar.tsx
  apps/web/common/components/SearchBar/SearchBarNoHero.tsx
  apps/web/common/components/SliderImages.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/next.config.js
  pnpm-lock.yaml
Labels: enhancement, story, backend, frontend

#835 [Epic - Main] Updates from comments
  apps/web/app/(blog-guide)/layout.tsx
  apps/web/app/(listings)/layout.tsx
  apps/web/common/components/Header.tsx
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/common/components/SearchBar/SearchBar.tsx
  apps/web/common/components/SearchBar/SearchBarNoHero.tsx
  apps/web/common/components/SliderImages.tsx
  apps/web/module/Accommodation/components/ImageGallery.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/RestaurantLocation.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/components/ChefsNote.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/PopularGuides.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
  apps/web/module/LandingPage/components/Slider.tsx
  apps/web/module/LandingPage/components/TravelSlider.tsx
  apps/web/module/LandingPage/index.tsx
  apps/web/next.config.js
  pnpm-lock.yaml
Labels: enhancement, frontend, epic, host account

#837 [Story-Feature] Create tabs for rental and properties calendar
  apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
Labels: enhancement, story, frontend, host account

#838 [Epic - Main] Updates from Calendar reservations
  .gitignore
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/beds/page.tsx
  apps/web/app/(host)/hosting/reservations/calendar/properties/rooms/page.tsx
  apps/web/app/(host)/hosting/reservations/calendar/properties/whole-places/page.tsx
  apps/web/common/components/HostLayout/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarBed.ts
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarRoom.ts
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarWholePlace.ts
  apps/web/module/Hosting/Reservations/Upcoming/index.tsx
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
Labels: enhancement, backend, frontend, epic, host account

#841 [Hotfix] Change to webURL all localhost url on guides pages
  CHANGELOG.md
  apps/web/module/BlogGuide/Guide/RestaurantGuide/index.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/index.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/index.tsx
Labels: enhancement, frontend, hotfix

#859 [Story-Feature] Added divider on user dropdown menu on header
  apps/web/common/components/Header/LoggedInUserDropdown.tsx
  pnpm-lock.yaml
Labels: frontend, task, host account

#860 [Story-Feature] Guide map change favicon
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/common/components/SpecificMap.tsx
  apps/web/module/Guides/Restaurant/index.tsx
  apps/web/module/Guides/Surfing/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
  apps/web/module/Hosting/Listings/Activities/Activity/Itinerary/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Location.tsx
  apps/web/module/Hosting/Listings/Rentals/Rental/Location/index.tsx
  apps/web/public/restaurant-map-icon.png
  apps/web/public/surf-map-icon.png
Labels: enhancement, story, frontend, host account

#866 [ Story - Feature ] Backend get property calendars
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
Labels: enhancement, backend, task, host account

#868 [ Story - Feature ] Custom hooks for get property
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarProperty.ts
Labels: frontend, task, host account

#867 [Story - Feature] Tabs for rentals will be show only the type that has items
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetRentalCounts.ts
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
  apps/web/module/Hosting/Reservations/components/ReservationCalendarTab.tsx
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
Labels: frontend, task, host account

#861 [Story-Feature] Guide map change favicon
  apps/web/common/components/MultipleMarkerMap.tsx
  apps/web/module/Guides/Islands/index.tsx
  apps/web/module/Guides/components/GuideContent.tsx
  apps/web/public/island-map-icon-1.png
  apps/web/public/island-map-icon-2.png
Labels: enhancement, story, frontend, host account

#870 [ Feature - Epic] Created and implemented edit rental child name to frontend
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/basicInfo.ts
  apps/api/src/routes/api/rentals-v2/services/calendar.ts
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useUpdateVehicleName.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  packages/database/mongo/models/dbRentals.ts
Labels: story, backend, frontend, host account

#869 [Story-Feature] Legends for calendar priorities need to apply the initial ui
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
  apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
  apps/web/module/Hosting/Reservations/components/LegendModal.tsx
  apps/web/module/Hosting/Reservations/helpers/legends.ts
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
Labels: enhancement, frontend, task, host account

#871 [Feature - Epic] 8 23 2024 comments
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/web/common/components/Header/LoggedInUserDropdown.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetRentalCounts.ts
  apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
  apps/web/module/Hosting/Reservations/components/LegendModal.tsx
  apps/web/module/Hosting/Reservations/components/ReservationCalendarTab.tsx
  apps/web/module/Hosting/Reservations/helpers/legends.ts
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  pnpm-lock.yaml
Labels: enhancement, story, frontend, host account

#872 [Epic - Main] Updates from comments
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/web/common/components/Header/LoggedInUserDropdown.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetRentalCounts.ts
  apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
  apps/web/module/Hosting/Reservations/components/LegendModal.tsx
  apps/web/module/Hosting/Reservations/components/ReservationCalendarTab.tsx
  apps/web/module/Hosting/Reservations/helpers/legends.ts
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  pnpm-lock.yaml
Labels: enhancement, frontend, epic, host account

#874 [Main - Epic] Sync Updates from Main to Calendar
  apps/api/src/routes/api/rentals-v2/index.ts
  apps/api/src/routes/api/rentals-v2/services/default.ts
  apps/web/common/components/Header/LoggedInUserDropdown.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetRentalCounts.ts
  apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
  apps/web/module/Hosting/Reservations/components/LegendModal.tsx
  apps/web/module/Hosting/Reservations/components/ReservationCalendarTab.tsx
  apps/web/module/Hosting/Reservations/helpers/legends.ts
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
  apps/web/module/Hosting/Reservations/types/CalendarTable.d.ts
  pnpm-lock.yaml
Labels: enhancement, backend, frontend, epic, host account

#876 [Story-Feature] Connect frontend to backend property calendar reservations
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/page.tsx
  apps/web/common/components/HostLayout/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/ReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
  apps/web/module/Hosting/Reservations/helpers/reservationCalendarTabs.tsx
Labels: enhancement, frontend, task, host account

#877 [Feature - Epic] Maked the property calendar reservations all unit types
  apps/api/src/routes/api/properties-v2/index.ts
  apps/api/src/routes/api/properties-v2/services/calendar.ts
  apps/api/src/routes/api/properties-v2/services/units.ts
  apps/web/app/(host)/hosting/reservations/calendar/properties/page.tsx
  apps/web/common/components/HostLayout/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/ReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
  apps/web/module/Hosting/Reservations/Calendar/hooks/useGetCalendarProperty.ts
Labels: enhancement, story, frontend, host account

#879 [Epic - Main] Added terms and use
  apps/cms/src/collections/Legal/index.ts
  apps/cms/src/payload.config.ts
  apps/web/app/(legal)/legal/[legal-name-from-cms]/page.tsx
  apps/web/app/(legal)/legal/layout.tsx
  apps/web/module/Legal/index.tsx
Labels: feature, frontend

#880 [Story-Feature] Implement Legends to rental and properties
  apps/web/module/Hosting/Reservations/Calendar/Activity/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Activity/SampleData.json
  apps/web/module/Hosting/Reservations/Calendar/Activity/index.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/BedReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/CalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/ReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/RoomReservationCalendar.tsx.tsx
  apps/web/module/Hosting/Reservations/Calendar/Property/WholePlaceReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeCalendarTable.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/BikeReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/CarReservationCalendar.tsx
  apps/web/module/Hosting/Reservations/Calendar/Rental/MotorReservationCalendar.ts.tsx
  apps/web/module/Hosting/Reservations/Calendar/Sidebar.tsx
  apps/web/module/Hosting/Reservations/components/CalendarLegend.tsx
  apps/web/module/Hosting/Reservations/components/CalendarTab.tsx
  apps/web/module/Hosting/Reservations/components/LegendModal.tsx
  apps/web/module/Hosting/Reservations/components/ReservationTab.tsx
  apps/web/module/Hosting/Reservations/helpers/legends.ts
Labels: enhancement, story, frontend, host account

#885 [Story-Feature] All inputs radius standard
  apps/web/common/components/ui/Input.tsx
  apps/web/common/components/ui/Select.tsx
  apps/web/common/components/ui/Typography.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
Labels: frontend, task, host account

#886 [Story-Feature] adjusted listing units pagination to make the pagination work
  apps/web/module/Hosting/Listings/Activities/index.tsx
  apps/web/module/Hosting/Listings/Properties/index.tsx
Labels: frontend, task, host account

#887 [Feature- Epic] Updates from 8-23-2024 comments
  apps/web/common/components/ui/Input.tsx
  apps/web/common/components/ui/Select.tsx
  apps/web/common/components/ui/Typography.tsx
  apps/web/module/Hosting/Listings/Activities/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/index.tsx
Labels: enhancement, story, frontend

#889 [Epic - Main] Updates from comments
  apps/web/common/components/ui/Input.tsx
  apps/web/common/components/ui/Select.tsx
  apps/web/common/components/ui/Typography.tsx
  apps/web/module/Hosting/Listings/Activities/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Units/Edit/WholePlace.tsx
  apps/web/module/Hosting/Listings/Properties/index.tsx
Labels: enhancement, frontend, epic, host account

#890 [Feature] - Make the global-error.tsx design consistent with the app theme
  apps/web/app/(error)/error/layout.tsx
  apps/web/app/(error)/error/page.tsx
  apps/web/module/Error/global-error.tsx
Labels: frontend
