Repository explore-siargao/es-main, pull requests merged in 2024-12, with the labels that each got.

#1371 Added manual card and save card payment
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/api/src/routes/api/xendit/services/default.ts
  apps/web/common/components/ui/Select2.tsx
  apps/web/module/Admin/Listings/ForReview/Property/Reviews/index.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
  apps/web/module/Cart/cart-summary/index.tsx
  apps/web/module/Cart/components/cart-list.tsx
  apps/web/module/Cart/components/sub-total-box.tsx
  apps/web/module/Cart/hooks/use-add-card-payment.ts
  apps/web/module/Cart/hooks/use-add-gcash-payment.ts
  apps/web/module/Cart/hooks/use-add-manual-card-payment.ts
  apps/web/module/Cart/index.tsx
  apps/web/module/Cart/pay/index.tsx
  apps/web/module/Cart/pay/payment-method-form.tsx
  apps/web/module/Cart/pay/payment-options.tsx
  apps/web/module/Cart/pay/payment-saved-form.tsx
  apps/web/module/Cart/pay/store/usePaymentInfoStore.ts
  apps/web/module/Hosting/Listings/Properties/Property/Reviews/index.tsx
  apps/web/module/Listing/Property/components/hero.tsx
  apps/web/module/Listing/Property/types/AvailableBooking.ts
  apps/web/module/Listing/Property/types/SectionInfo.d.ts
  packages/contract-2/src/cart/zod.ts
  packages/contract-2/src/reservations/reservation.ts
Labels: backend, frontend, minor, listing, cart

#1373 Added input and output zod validation in filters endpoint
  apps/api/src/routes/api/activities/services/filtered.ts
  apps/api/src/routes/api/properties/services/filtered.ts
  apps/api/src/routes/api/rentals/services/filtered.ts
  apps/web/common/components/custom-square-slider.tsx
  apps/web/module/search/activities/card.tsx
  packages/contract-2/src/address-location/zod.ts
  packages/contract-2/src/photos/zod.ts
  packages/contract-2/src/rentals/zod.ts
  packages/contract-2/src/search-filters/enum.ts
  packages/contract-2/src/search-filters/zod.ts
  packages/seeder/src/activities-joiner.ts
  packages/seeder/src/activities-private.ts
Labels: enhancement, backend, search, contract

#1374 Fixed bug on resetting finishSections in all categories
  apps/api/src/routes/api/activities/services/activity-inclussions.ts
  apps/api/src/routes/api/activities/services/additionalInfo.ts
  apps/api/src/routes/api/activities/services/basic-info.ts
  apps/api/src/routes/api/activities/services/default.ts
  apps/api/src/routes/api/activities/services/finishedSection.ts
  apps/api/src/routes/api/activities/services/price-slots.ts
  apps/api/src/routes/api/properties/services/default.ts
  apps/api/src/routes/api/properties/services/facilities.ts
  apps/api/src/routes/api/properties/services/finishedSections.ts
  apps/api/src/routes/api/properties/services/policies.ts
  apps/api/src/routes/api/rentals/services/addOns.ts
  apps/api/src/routes/api/rentals/services/basicInfo.ts
  apps/api/src/routes/api/rentals/services/details.ts
  apps/api/src/routes/api/rentals/services/finishedSections.ts
  apps/api/src/routes/api/rentals/services/locations.ts
  apps/api/src/routes/api/rentals/services/rates.ts
  packages/seeder/src/properties.ts
Labels: bug, enhancement, backend, listing

#1376 Added endpoint for book now functions
  apps/api/src/routes/api/for-payment-listings/index.ts
  apps/api/src/routes/api/for-payment-listings/services/default.ts
  apps/api/src/routes/api/reservations/index.ts
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/api/src/routes/api/reservations/services/default.ts
  apps/api/src/routes/api/reservations/services/for-payment-reservation.ts
  apps/api/src/routes/index.ts
  packages/contract-2/package.json
  packages/contract-2/src/for-payment-listings/for-payment.ts
  packages/contract-2/src/for-payment-listings/index.ts
  packages/contract-2/src/for-payment-listings/type.ts
  packages/contract-2/src/for-payment-listings/zod.ts
  packages/contract-2/src/reservations/reservation.ts
  packages/database/mongo/models/dbForPaymentListings.ts
  packages/database/mongo/models/dbReservations.ts
  packages/database/mongo/models/index.ts
Labels: enhancement, database, backend, payments

#1379 Added convertion of prices in all public page categories
  apps/api/src/routes/api/activities/services/default.ts
  apps/api/src/routes/api/properties/services/default.ts
  apps/api/src/routes/api/rentals/services/default.ts
Labels: enhancement, backend, listing

#1383 Adjusted cart endpoints added comission and computation of price
  apps/api/src/routes/api/carts/services/default.ts
  apps/web/module/Cart/checkout/property-more-info.tsx
  packages/constants/src/index.ts
  packages/contract-2/src/cart/zod.ts
  packages/contract/src/BackendResponse/zod.ts
  packages/database/mongo/models/dbCarts.ts
Labels: enhancement, database, backend, cart

#1386 Added rental policies and modified type of daysCanCancel
  apps/api/src/routes/api/properties/services/units.ts
  apps/api/src/routes/api/rentals/index.ts
  apps/api/src/routes/api/rentals/services/additionalInfo.ts
  apps/api/src/routes/api/rentals/services/basicInfo.ts
  apps/api/src/routes/api/reservations/services/activityReservation.ts
  apps/api/src/routes/api/reservations/services/rentalReservation.ts
  apps/api/src/routes/api/reservations/services/unitsReservation.ts
  packages/contract-2/src/activity/zod.ts
  packages/contract-2/src/property/zod.ts
  packages/contract-2/src/rentals/rental.ts
  packages/contract-2/src/rentals/type.ts
  packages/contract-2/src/rentals/zod.ts
  packages/contract/src/Rental/type.ts
  packages/contract/src/Rental/zod.ts
  packages/database/mongo/models/dbActivities.ts
  packages/database/mongo/models/dbBookableUnitTypes.ts
  packages/database/mongo/models/dbRentals.ts
  packages/seeder/src/activities-joiner.ts
  packages/seeder/src/activities-private.ts
  packages/seeder/src/properties.ts
  packages/seeder/src/rentals.ts
Labels: enhancement, database, backend, listing

#1390 Adjusted for-payments and add computations
  apps/api/src/routes/api/carts/services/default.ts
  apps/api/src/routes/api/for-payment-listings/services/default.ts
  packages/contract-2/src/for-payment-listings/zod.ts
  packages/database/mongo/models/dbForPaymentListings.ts
Labels: enhancement, database, backend, payments

#1397 Added example code for implementing HMAC
  apps/api/src/routes/api/for-payment-listings/services/default.ts
  apps/api/src/routes/api/testing/default.ts
  apps/api/src/routes/api/testing/index.ts
  apps/api/src/routes/index.ts
  packages/contract-2/src/for-payment-listings/zod.ts
  packages/database/mongo/models/dbForPaymentListings.ts
  packages/database/mongo/models/dbTestting.ts
  packages/database/mongo/models/index.ts
  packages/services/src/hmac.ts
Labels: backend

#1399 Added hmac to manual and linking card in carts to reservation and for payments to reservation
  apps/api/src/routes/api/rentals/services/calendar.ts
  apps/api/src/routes/api/rentals/services/filtered.ts
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/api/src/routes/api/reservations/services/for-payment-reservation.ts
  apps/web/app/(listings)/listings/rentals/[rentalId]/page.tsx
  apps/web/module/BlogGuide/Guide/RestaurantGuide/SectionInfo.tsx
  apps/web/module/Hosting/components/dummy.tsx
  apps/web/module/Listing/Activity/hero.tsx
  apps/web/module/Listing/Property/components/available-booking.tsx
  apps/web/module/Listing/Property/components/checkout-box.tsx
  apps/web/module/Listing/Property/components/image-gallery.tsx
  apps/web/module/Listing/Property/components/modals/checkout-more-info-modal.tsx
  apps/web/module/Listing/Property/types/AvailableBooking.ts
  apps/web/module/Listing/Rental/about.tsx
  apps/web/module/Listing/Rental/checkout-box.tsx
  apps/web/module/Listing/Rental/components/BookingDescription.tsx
  apps/web/module/Listing/Rental/components/CheckoutBox.tsx
  apps/web/module/Listing/Rental/components/ContactHost.tsx
  apps/web/module/Listing/Rental/components/Directions.tsx
  apps/web/module/Listing/Rental/components/Highlights.tsx
  apps/web/module/Listing/Rental/components/HighlightsSection.tsx
  apps/web/module/Listing/Rental/components/IconDescription.tsx
  apps/web/module/Listing/Rental/components/IconTitleDescription.tsx
  apps/web/module/Listing/Rental/components/Inclusions.tsx
  apps/web/module/Listing/Rental/components/SummaryInfo.tsx
  apps/web/module/Listing/Rental/components/modals/CheckInOutModal.tsx
  apps/web/module/Listing/Rental/components/modals/CheckoutBreakdownModal.tsx
  apps/web/module/Listing/Rental/components/modals/ModalReporting.tsx
  apps/web/module/Listing/Rental/hero.tsx
  apps/web/module/Listing/Rental/host-information/avatar-title-description.tsx
  apps/web/module/Listing/Rental/host-information/index.tsx
  apps/web/module/Listing/Rental/image-gallery.tsx
  apps/web/module/Listing/Rental/inclusions.tsx
  apps/web/module/Listing/Rental/index.tsx
  apps/web/module/Listing/Rental/modals/checkout-more-info-modal.tsx
  apps/web/module/Listing/Rental/modals/image-gallery-modal.tsx
  apps/web/module/Listing/Rental/modals/price-breakdown-modal.tsx
  apps/web/module/Listing/Rental/modals/report-listing-modal.tsx
  apps/web/module/Listing/Rental/modals/share-modal.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/Category.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/HorizontalRatingSummary.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/OverallRating.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/RatingSummary.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/Review.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/UserReviews.tsx
  apps/web/module/Listing/Rental/modals/user-review-modal/index.tsx
  apps/web/module/Listing/Rental/pickup-location.tsx
  apps/web/module/Listing/Rental/requirements.tsx
  apps/web/module/Listing/Rental/share-save.tsx
  apps/web/module/Listing/Rental/similar-rentals.tsx
  apps/web/module/Listing/Rental/stores/use-pickup-dropoff-store.ts
  apps/web/module/Listing/Rental/title-section.tsx
  packages/contract-2/package.json
  packages/contract-2/src/cart/cart.ts
  packages/contract-2/src/for-payment-listings/zod.ts
  packages/contract-2/src/rentals/zod.ts
  packages/seeder/src/rentals.ts
Labels: enhancement, backend, payments

#1400 Modified the price base of total amount for all payments reservations
  apps/api/src/routes/api/reservations/helpers/totalPrice.ts
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/api/src/routes/api/reservations/services/for-payment-reservation.ts
  packages/contract-2/src/for-payment-listings/zod.ts
Labels: enhancement, backend, payments

#1401 Removed dayjs in basecode and converted it to date-fns
  CHANGELOG.md
  apps/api/package.json
  apps/api/src/routes/api/testing/default.ts
  apps/api/src/routes/api/testing/index.ts
  apps/api/src/routes/api/users/services/auth.ts
  apps/api/src/routes/index.ts
  apps/web/module/AccountSettings/LoginSecurity/UpdatePassword.tsx
  apps/web/module/Authentication/components/SignUpForm.tsx
  apps/web/module/Authentication/constants/index.ts
  apps/web/package.json
Labels: enhancement, backend, frontend, cleanup

#1403 When changing property types reset units list on that property fixed
  apps/api/src/routes/api/properties/services/default.ts
Labels: enhancement, backend, listing
