Repository explore-siargao/es-main, pull requests merged in 2025-01, with the labels that each got.

#1427 add guest management modals and store for activity listings
  apps/web/module/Listing/activity/checkout-box.tsx
  apps/web/module/Listing/activity/index.tsx
  apps/web/module/Listing/activity/modals/guest-add-modal.tsx
  apps/web/module/Listing/activity/modals/price-breakdown-modal.tsx
  apps/web/module/Listing/activity/stores/use-guests-store.ts
Labels: frontend, listing

#1428 update guest capacity handling in checkout and guest add modal
  apps/web/module/Listing/Property/checkout-box.tsx
  apps/web/module/Listing/Property/modals/guest-add-modal.tsx
Labels: listing

#1431 Modified property filter endpoint
  apps/api/src/routes/api/properties/services/filtered.ts
Labels: enhancement, backend, client feedback

#1433 Fixed error on searching activity with numberOfGuest
  apps/api/src/routes/api/activities/services/filtered.ts
Labels: bug, backend

#1438 added cart property and rental item modify function
  apps/web/common/helpers/combine-date-time.ts
  apps/web/common/store/use-modal-store.ts
  apps/web/module/Listing/rental/checkout-box.tsx
  apps/web/module/Listing/rental/modals/pick-up-drop-off-modal.tsx
  apps/web/module/cart/cart-summary/index.tsx
  apps/web/module/cart/index.tsx
  apps/web/module/cart/lists/index.tsx
  apps/web/module/cart/lists/property-item.tsx
  apps/web/module/cart/lists/rental-item.tsx
  apps/web/module/cart/modals/check-in-out-modal.tsx
  apps/web/module/cart/modals/delete-all-selected-items-modal.tsx
  apps/web/module/cart/modals/delete-cart-item-modal.tsx
  apps/web/module/cart/modals/guest-add-modal.tsx
  apps/web/module/cart/modals/pick-up-drop-off-modal.tsx
  apps/web/module/cart/modals/update-property-item-modal.tsx
  apps/web/module/cart/modals/update-rental-item-modal.tsx
  apps/web/module/cart/stores/use-cart-store.ts
  apps/web/module/cart/stores/use-check-in-out-date-store.ts
  apps/web/module/cart/stores/use-guests-store.ts
  apps/web/module/cart/stores/use-pickup-dropoff-store.ts
Labels: listing, cart

#1442 Reset all data when changing property type
  apps/api/src/routes/api/properties/services/default.ts
Labels: enhancement, backend, listing

#1434 Created Gcash Checkout
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/web/module/cart/checkout/index.tsx
  apps/web/module/cart/hooks/use-add-gcash-payment.ts
  packages/contract-2/src/cart/zod.ts
Labels: cart, payments

#1443 Created Saved Card Checkout
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/web/module/cart/checkout/index.tsx
  apps/web/module/cart/hooks/use-add-card-payment.ts
  apps/web/module/landing-page/index.tsx
  apps/web/next.config.js
  packages/contract-2/src/reservations/reservation.ts
Labels: cart, payments

#1445 Checkout using manual card
  apps/api/src/routes/api/reservations/services/cart-reservations.ts
  apps/web/module/cart/checkout/index.tsx
  apps/web/module/cart/hooks/use-add-manual-card-payment.ts
  packages/contract-2/src/reservations/reservation.ts
Labels: cart, payments

#1452 Added endpoint for getting guest list reservations separated by cancelled, done and active reservations
  apps/api/package.json
  apps/api/src/routes/api/properties/services/filtered.ts
  apps/api/src/routes/api/reservations/index.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/index.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/active-reservation.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/cancelled-reservation.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/finish-reservation.ts
  packages/contract-2/src/activity/zod.ts
  packages/contract-2/src/address-location/zod.ts
  packages/contract-2/src/guest/zod.ts
  packages/contract-2/src/host/zod.ts
  packages/contract-2/src/property/zod.ts
  packages/contract-2/src/rentals/zod.ts
  packages/contract-2/src/reservations/reservation.ts
  packages/contract-2/src/reservations/type.ts
  packages/contract-2/src/reservations/zod.ts
  packages/seeder/src/properties.ts
  pnpm-lock.yaml
Labels: backend, guest, payments

#1453 feat(web): added PropertyTypeChangeModal and update handlesave logic
  apps/web/module/Hosting/Listings/Properties/Property/PropertyType.tsx
  apps/web/module/Hosting/Listings/Properties/modals/property-type-change-modal.tsx
Labels: frontend, listing

#1468 Added seeder for reviews
  apps/api/src/routes/api/activities/services/default.ts
  apps/api/src/routes/api/activities/services/review.ts
  apps/api/src/routes/api/properties/services/default.ts
  apps/api/src/routes/api/properties/services/review.ts
  apps/api/src/routes/api/rentals/services/default.ts
  apps/api/src/routes/api/rentals/services/review.ts
  packages/contract-2/src/property/zod.ts
  packages/contract-2/src/rentals/zod.ts
  packages/contract-2/src/review/type.ts
  packages/contract-2/src/review/zod.ts
  packages/database/mongo/models/dbReviews.ts
  packages/seeder/index.ts
  packages/seeder/src/common/constants/reviews.ts
  packages/seeder/src/reviews.ts
Labels: enhancement, database, backend

#1455 added startDate time and endDate time
  apps/web/module/cart/lists/activity-item.tsx
  apps/web/module/cart/lists/property-item.tsx
  apps/web/module/cart/lists/rental-item.tsx
Labels: frontend

#1467 added update guestModal for search guest
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/guest-add-modal.tsx
Labels: Frontend, Guest

#1486 Add card badge for private or joiner activity for its listing
  apps/api/src/routes/api/activities/services/filtered.ts
  apps/web/app/(listings)/listings/properties/[propertyId]/message/page.tsx
  apps/web/common/components/Header/filter/constants.ts
  apps/web/common/components/SearchBar/ActivitiesSearchBar/index.tsx
  apps/web/common/components/SearchBar/PropertySearchBar/index.tsx
  apps/web/common/components/SearchBar/RentalsSearchBar/index.tsx
  apps/web/module/Listing/Property/available-units.tsx
  apps/web/module/Listing/Property/checkout-box.tsx
  apps/web/module/Listing/Property/index.tsx
  apps/web/module/Listing/activity/index.tsx
  apps/web/module/Listing/property/message2.tsx
  apps/web/module/Listing/rental/index.tsx
  apps/web/module/cart/modals/activity-guest-add-modal.tsx
  apps/web/module/cart/modals/update-activity-item-modal.tsx
  apps/web/module/landing-page/index.tsx
  apps/web/module/search/activities/card.tsx
  apps/web/module/search/components/experience-type-tag.tsx
  packages/contract-2/src/activity/enum.ts
  packages/contract-2/src/activity/index.ts
  packages/contract-2/src/activity/zod.ts
  packages/contract-2/src/search-filters/enum.ts
  packages/contract-2/src/search-filters/zod.ts
Labels: Backend, Frontend, Guest

#1487 Update experienceType to use E_Experience_Types for join…
  packages/seeder/src/activities-joiner.ts
  packages/seeder/src/activities-private.ts
Labels: Database

#1504 Fix checkoutbox text for experience type
  apps/api/src/routes/api/properties-v2/services/unitPrice.ts
  apps/api/src/routes/api/properties/services/filtered.ts
  apps/web/common/components/Header/filter/index.tsx
  apps/web/module/Listing/activity/checkout-box.tsx
  apps/web/module/search/activities/card.tsx
Labels: Backend, Frontend, Patch

#1528 Update padding values for width variants
  apps/web/common/components/Wrappers/WidthWrapper.tsx
Labels: Frontend, Guest

#1531 Update payment information in SubTotalBox component
  apps/web/module/cart/sub-total-box.tsx
Labels: Frontend, Patch

#1535 Update pricing display to consistently show price per person
  apps/web/module/landing-page/activities-slider/card.tsx
  apps/web/module/search/activities/card.tsx
Labels: Frontend, Patch

#1536 fix error on searchingfiltering properties
  apps/api/src/routes/api/properties/services/filtered.ts
  packages/contract-2/src/search-filters/zod.ts
Labels: Backend, Patch, Guest

#1537 adjusted endpoint related to private activities and seeder
  apps/api/src/routes/api/activities/services/filtered.ts
  apps/api/src/routes/api/activities/services/price-slots.ts
  packages/contract/src/Activities/zod.ts
  packages/seeder/src/activities-private.ts
Labels: Backend, Host, Minor

#1538 Consolidate ShareSave component imports and remove redundant file
  apps/web/module/Blog/BlogImages.tsx
  apps/web/module/BlogGuide/Guide/SurfingGuide/SurfGuide.tsx
  apps/web/module/BlogGuide/Guide/TravelBlog/TravelImages.tsx
  apps/web/module/Listing/Property/hero.tsx
  apps/web/module/Listing/Property/modals/image-gallery-modal.tsx
  apps/web/module/Listing/Property/share-save.tsx
  apps/web/module/Listing/activity/hero.tsx
  apps/web/module/Listing/modals/share-modal.tsx
  apps/web/module/Listing/rental/hero.tsx
  apps/web/module/Listing/rental/modals/image-gallery-modal.tsx
  apps/web/module/Listing/rental/modals/share-modal.tsx
  apps/web/module/Listing/share-save.tsx
Labels: Frontend, Minor

#1539 fixed activities filtering endpoint and adjusted the pricePerPerson types
  apps/api/src/routes/api/activities/index.ts
  apps/api/src/routes/api/activities/services/filtered.ts
  apps/api/src/routes/api/activities/services/highest-price.ts
  apps/api/src/routes/api/activities/services/price-slots.ts
  packages/contract/src/Activities/zod.ts
  packages/seeder/src/activities-private.ts
Labels: Backend, Patch, Guest

#1540 fixed error on filtering rentals
  apps/api/src/routes/api/rentals/services/filtered.ts
Labels: Backend, Patch, Guest

#1542 added endpoint for adding wishlist and create database for wishlist
  apps/api/src/routes/api/wishlists/helpers/fn.ts
  apps/api/src/routes/api/wishlists/index.ts
  apps/api/src/routes/api/wishlists/services/default.ts
  apps/api/src/routes/index.ts
  packages/database/mongo/models/dbWishlists.ts
  packages/database/mongo/models/index.ts
Labels: Backend, Minor, Guest

#1545 added endpoint for get all wishlist by category
  apps/api/src/routes/api/wishlists/index.ts
  apps/api/src/routes/api/wishlists/services/default.ts
Labels: Database, Backend, Minor, Guest

#1546 Before creating a listing host need to agree in the tc
  apps/web/common/components/AdminLayout/ListingActivityHeader.tsx
  apps/web/common/components/AdminLayout/ListingHeader.tsx
  apps/web/common/components/AdminLayout/ListingRentalHeader.tsx
  apps/web/common/components/HostLayout/Header.tsx
  apps/web/common/components/HostLayout/ListingHeader/index.tsx
  apps/web/module/Listing/modals/terms-and-conditions-modal.tsx
Labels: Frontend, For Refinement, Question

#1553 added endpoint for get wishlist per category
  apps/api/src/routes/api/wishlists/services/default.ts
  packages/contract-2/package.json
  packages/contract-2/src/wishlist/enum.ts
  packages/contract-2/src/wishlist/index.ts
  packages/contract-2/src/wishlist/type.ts
  packages/contract-2/src/wishlist/wishlist.ts
  packages/contract-2/src/wishlist/zod.ts
  packages/database/mongo/models/dbWishlists.ts
Labels: Backend, Minor, Guest

#1544 Create booking list UI separate active finish and cancelled booking
  apps/api/src/routes/api/reservations/services/grouped-reservations/index.ts
  apps/api/src/routes/api/reservations/services/grouped-reservations/pipelines/groupedReservationPipeline.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/index.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/active-reservation.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/cancelled-reservation.ts
  apps/api/src/routes/api/reservations/services/guest-reservations/pipelines/finish-reservation.ts
  apps/web/app/(bookings)/bookings/active/page.tsx
  apps/web/app/(bookings)/bookings/cancelled/page.tsx
  apps/web/app/(bookings)/bookings/finished/page.tsx
  apps/web/app/(bookings)/bookings/group/page.tsx
  apps/web/app/(bookings)/bookings/layout.tsx
  apps/web/app/(bookings)/bookings/page.tsx
  apps/web/app/(bookings)/bookings/single/page.tsx
  apps/web/module/Bookings/booking-tabs.tsx
  apps/web/module/Bookings/group.tsx
  apps/web/module/Bookings/hooks/use-get-group-reservations.ts
  apps/web/module/Bookings/hooks/use-get-reservations.ts
  apps/web/module/Bookings/index.tsx
  apps/web/module/Bookings/single.tsx
  apps/web/module/Bookings/sub-total-box.tsx
  apps/web/module/Bookings/view-payment.tsx
  apps/web/module/cart/checkout/more-info/activity/contacts.tsx
  apps/web/module/cart/checkout/more-info/activity/index.tsx
  apps/web/module/cart/checkout/more-info/property/contacts.tsx
  apps/web/module/cart/checkout/more-info/property/index.tsx
  apps/web/module/cart/checkout/more-info/rental/contacts.tsx
  apps/web/module/cart/checkout/more-info/rental/index.tsx
  apps/web/module/cart/checkout/price-details-box/activity.tsx
  apps/web/module/cart/checkout/price-details-box/property.tsx
  apps/web/module/cart/checkout/price-details-box/rental.tsx
  apps/web/module/cart/index.tsx
  packages/contract-2/src/government-id/zod.ts
  packages/contract-2/src/guest/zod.ts
  packages/contract-2/src/reservations/reservation.ts
Labels: Frontend, Guest

#1554 1507 cart select all button is always selected
  apps/web/module/cart/lists/index.tsx
Labels: Frontend, Patch

#1555 added seeder for wishlist
  packages/seeder/index.ts
  packages/seeder/src/wishlist.ts
Labels: Database, Patch

#1559 CMS blogs enhancement
  apps/cms/package.json
  apps/cms/src/collections/Blogs/index.tsx
  apps/cms/src/fields/blogs/content.ts
  apps/cms/src/fields/blogs/hero.ts
  apps/cms/src/fields/blogs/sideContent.ts
  apps/web/common/components/RichText/serialize.tsx
  apps/web/common/components/Wrappers/YMarginWrapper.tsx
  apps/web/module/Blog/BlogImages.tsx
  apps/web/module/Blog/PopularBlogs.tsx
  apps/web/module/Blog/image-gallery.tsx
  apps/web/module/Blog/index.tsx
  apps/web/module/Hosting/Listings/Activities/Activity/Pricing/index.tsx
  pnpm-lock.yaml
Labels: CMS

#1562 Fix error on image carousel on search filter results
  apps/web/common/components/custom-square-slider.tsx
Labels: Frontend, Guest

#1563 Update private activity setup on host to show price per person and price per slot input
  apps/web/module/Hosting/Listings/Activities/Activity/Pricing/index.tsx
Labels: Host, Patch

#1564 Connect backend get reviews to single public page frontend
  apps/web/common/types/global.ts
  apps/web/module/Admin/Listings/ForReview/Property/Reviews/index.tsx
  apps/web/module/Hosting/Listings/Properties/Property/Reviews/index.tsx
  apps/web/module/Listing/Property/index.tsx
  apps/web/module/Listing/Property/types/RatingSummary.d.ts
  apps/web/module/Listing/activity/index.tsx
  apps/web/module/Listing/modals/user-review-modal.tsx
  apps/web/module/Listing/rental/index.tsx
  apps/web/module/Listing/rental/types/RatingSummary.d.ts
  apps/web/module/Listing/reviews/category.tsx
  apps/web/module/Listing/reviews/horizontal-rating-summary.tsx
  apps/web/module/Listing/reviews/overall-rating.tsx
  apps/web/module/Listing/reviews/rating-summary.tsx
  apps/web/module/Listing/reviews/review.tsx
  apps/web/module/Listing/reviews/star-rating.tsx
  apps/web/module/Listing/reviews/user-reviews.tsx
  packages/contract-2/src/activity/zod.ts
  packages/contract-2/src/property/zod.ts
  packages/contract-2/src/rentals/zod.ts
Labels: Backend, Frontend

#1574 created seeder for host approvals
  apps/api/src/routes/api/host-approvals/services/default.ts
  packages/contract-2/package.json
  packages/contract-2/src/host-approval/index.ts
  packages/database/mongo/models/dbHostApproval.ts
  packages/seeder/index.ts
  packages/seeder/src/host-approval.ts
  packages/seeder/src/users.ts
Labels: Database, Backend, Host, Minor, Admin

#1580 added endpoint for gt all host approval by host
  apps/api/src/common/helpers/capitalizedFirstLetter.ts
  apps/api/src/routes/api/host-approvals/index.ts
  apps/api/src/routes/api/host-approvals/services/default.ts
  packages/contract-2/src/host-approval/enum.ts
  packages/contract-2/src/host-approval/host-approval.ts
  packages/contract-2/src/host-approval/index.ts
  packages/contract-2/src/host-approval/type.ts
  packages/contract-2/src/host-approval/zod.ts
  packages/seeder/src/host-approval.ts
  packages/seeder/src/users.ts
Labels: Database, Backend, Host, Minor

#1584 added endpoint for updating host approval by host
  apps/api/src/routes/api/host-approvals/index.ts
  apps/api/src/routes/api/host-approvals/services/default.ts
  packages/contract-2/src/host-approval/host-approval.ts
  packages/contract-2/src/host-approval/type.ts
  packages/contract-2/src/host-approval/zod.ts
Labels: Backend, Host, Minor

#1586 added endpoint for cancellation of host approval request
  apps/api/src/routes/api/host-approvals/index.ts
  apps/api/src/routes/api/host-approvals/services/default.ts
  packages/contract-2/src/host-approval/enum.ts
  packages/contract-2/src/host-approval/host-approval.ts
  packages/database/mongo/models/dbHostApproval.ts
Labels: Backend, Host, Minor

#1587 added endpoint for get all approvals by admin and endpoint for approve or reject by admin
  apps/api/src/routes/api/host-approvals/index.ts
  apps/api/src/routes/api/host-approvals/services/default.ts
  packages/contract-2/src/host-approval/host-approval.ts
  packages/contract-2/src/host-approval/type.ts
  packages/contract-2/src/host-approval/zod.ts
Labels: Backend, Host, Minor, Admin

#1588 Activity book now
  apps/web/module/Listing/activity/checkout-box.tsx
  apps/web/module/cart/book-now/index.tsx
Labels: Backend, Frontend
